home:
   path: /
   controller: App\Controller\HomeController
   methods: [GET]
display_form:
   path: /blogposts
   controller: App\Controller\ProductController
   methods: [GET]
add_article:
   path: /blogposts
   controller: App\Controller\AddProductController
   methods: [POST]
get_article:
  path: /{id}
  controller: App\Controller\GetProductController
