home:
   path: /
   controller: App\Controller\HomeController
display_form:
   path: /blogposts
   controller: App\Controller\ProductController
   methods: [GET]
add_article:
   path: /blogposts
   controller: App\Controller\AddProductController
   methods: [POST]
# getProduct:
#    path: /products/{id}
#    controller: App\Controller\GetProduct
# updateProduct:
#    path: /updateProduct/{id}
#    controller: App\Controller\UpdateProduct
