home:
   path: /
   controller: App\Controller\HomeController
getArticle:
  path: /article/{id}
  controller: App\Controller\GetArticle
createArticle:
  path: /blogposts
  controller: App\Controller\CreateArticle