home:
   path: /
   controller: App\Controller\HomeController
article:
  path: /article
  controller: App\Controller\ArticleController

getArticle:
  path: /article/{id}
  controller: App\Controller\GetArticle
createArticle:
  path: /blogposts
  controller: App\Controller\CreateArticle
updateArticle:
  path: /article/update/{id}
  controller: App\Controller\UpdateArticle