home:
    path: /
    controller: App\Controller\HomeController
product:
    path: /products
    controller: App\Controller\ProductController
deleteProduct:
    path: /products/delete/{id}
    controller: App\Controller\DeleteProduct
getProduct:
    path: /products/{id}
    controller: App\Controller\GetProduct
putProduct:
    path: /products/{id}/{name}
    controller: App\Controller\PutProduct
blogposts:
    path: /blogposts
    controller: App\Controller\GetAddArticle
    methods: ["GET","POST"]
