#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController
createArticle:
  path: /blogposts
  controller: App\Controller\CreateArticle